name: 🐛 报告BUG
description: 创建一个脚本的 BUG 报告
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 感谢你报告错误！⛰

        请填写此表单，帮助我们重现问题。

        - 标题必须格式为`[脚本名称-版本]:错误描述`，例如`[外语终结者-1.4.0.0]:无法加载模型`。
        - 该错误是由 xxxx脚本 引起的。如果我停用该脚本，则不会发生此问题。
        - 你必须完整的描述你使用的脚本名称和版本号以及你遇到的问题。

        包含的错误信息:

        - 错误的截图/视频/gif（如果是视觉的）
        - 控制台错误（如有）

  - type: textarea
    id: expected_behavior
    attributes:
      label: 预期行为
      description: 请描述在没有 bug 的情况下你期望看到的结果。
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 实际行为
      description: 请描述在 bug 出现时实际看到的结果。
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 复现步骤
      description: 请详细描述如何复现该 bug 的步骤,包括截图,发生的网页地址等
      placeholder: |
        1. 打开 xxx 页面
        2. 点击 yyy 按钮
        3. 滚动到 zzz 部分
        4. 看到错误
    validations:
      required: true

# https://github.com/WhiteSevs/TamperMonkeyScript/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1

  - type: dropdown
    id: scriptruncontainer
    attributes:
      label: 脚本管理器或浏览器
      description: "勾选运行脚本的容器"
      multiple: false
      options:
        - 请选择符合的一项，不符合将关闭该issue
        - Violentmonkey
        - Violentmonkey BETA
        - TamperMonkey
        - TamperMonkey BETA
        - ScriptCat
        - Stay
        - Via浏览器
        - X浏览器
        - 其它
    validations:
      required: true

  - type: input
    attributes:
      label: 脚本管理器或浏览器版本号
      description: "如果脚本运行的容器是浏览器扩展，请填写版本号"
      placeholder: "例如：v2.20.0"
    validations:
      required: false

  - type: input
    attributes:
      label: 使用的浏览器以及内核版本号
      description: "请填写运行脚本的浏览器及内核版本，如果是套壳浏览器，内核版本请填写webview的版本"
      placeholder: "例如：Edge 135.0.3179.85（x64)"
    validations:
      required: true
      
  - type: input
    attributes:
      label: 操作系统
      description: Windows 11 (x64)  / Mac os X 11 / Ubuntu 20.04 / iOS 14/ Android 11
      placeholder: "例如：Windows 11 (x64)"
    validations:
      required: true

  - type: input
    attributes:
      label: 脚本版本
      description: 请输入你正在使用的脚本版本
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: 其他信息
      description: 如果你有其他认为有助于解决此问题的信息，请在这里提供。
  - type: checkboxes
    attributes:
      label: 我已确认 BUG 真实存在
      options:
        - label: 该 BUG 真实存在，请尽快修复
          required: true
