name: 🐛 Bug Report
description: Create a bug report for a script
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # Thank you for reporting a bug! ⛰

        Please fill out this form to help us reproduce the problem.

        - The title must be in the format `[ScriptName-Version]:Description of the error`, e.g., `[LanguageTerminator-1.4.0.0]:Unable to load model`.
        - The bug is caused by the xxxx script. If I disable this script, the problem will not occur.
        - You must fully describe the script name and version you are using, as well as the problem you encountered.

        Include the following error information:

        - Screenshot/video/gif of the error (if visual)
        - Console error messages (if any)

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Please describe the result you expect to see when the bug does not occur.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Please describe the actual result you see when the bug occurs.
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Please describe in detail how to reproduce the bug, including screenshots and the webpage address where it occurs.
      placeholder: |
        1. Open xxx page
        2. Click yyy button
        3. Scroll to zzz section
        4. See the error
    validations:
      required: true

  - type: dropdown
    id: scriptruncontainer
    attributes:
      label: Script Manager or Browser
      description: "Select the container where the script runs"
      multiple: false
      options:
        - Please select the appropriate one; incorrect selection will result in this issue being closed
        - Violentmonkey
        - Violentmonkey BETA
        - TamperMonkey
        - TamperMonkey BETA
        - ScriptCat
        - Stay
        - Via Browser
        - X Browser
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: Script Manager or Browser Version
      description: "If the script runs in a browser extension, please enter its version number"
      placeholder: "Example: v2.20.0"
    validations:
      required: false

  - type: input
    attributes:
      label: Browser and Engine Version
      description: "Please provide the browser and engine version. If it is a shell browser, enter the webview version."
      placeholder: "Example: Edge 135.0.3179.85 (x64)"
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System
      description: Windows 11 (x64) / Mac OS X 11 / Ubuntu 20.04 / iOS 14 / Android 11
      placeholder: "Example: Windows 11 (x64)"
    validations:
      required: true

  - type: input
    attributes:
      label: Script Version
      description: Please enter the version of the script you are using
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: If you have other information that may help solve this problem, please provide it here.
  - type: checkboxes
    attributes:
      label: I confirm the bug really exists
      options:
        - label: This bug really exists, please fix it as soon as possible
          required: true
