name: ✨ 功能请求
description: 提出新的功能要求或改进建议
labels: ["feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 功能要求

        - 请简要描述您想要的功能或改进建议。
        - 标题必须格式化为`[脚本名称]:期望功能`，例如`[外语终结者]:支持新地址`。
        - 您可以提供屏幕截图/网页地址，以更好地显示你的想法。
        - 带有星号（*）的选项为必填，其他可选填。**如果你填写的资料不符合规范，维护者可能不予回复，并直接关闭这个 issue。**
        - 如果你可以自行添加这个功能，我们随时欢迎你提交 Pull Request，并将你的修改合并到上游。

 # https://github.com/WhiteSevs/TamperMonkeyScript/blob/master/.github/ISSUE_TEMPLATE/feature_request_zh.yml?plain=1

  - type: checkboxes
    id: ensure
    attributes:
      label: 先决条件
      description: "若以下任意选项不适用，请勿提交这个 issue，因为我们会把它关闭"
      options:
        - label: "本issue已加上**脚本名称与功能**"
          required: true
        - label: "我已经在[这里](https://github.com/ChinaGodMan/UserScripts/issues?q=is%3Aissue+label%3Aenhancement)找过我要提出的建议，**并且没有找到相关问题**"
          required: true
          
  - type: textarea
    id: user_stories
    attributes:
      label: 功能要求
      description: 描述您如何使用这个新功能的场景。
      placeholder: |
        作为一个 [角色]，我想要 [功能]，以便 [目标]。
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: 使用场景
      description: 列出您认为这个功能应该支持的使用场景、截图。
      placeholder: |
        1. 使用场景 1
        2. 使用场景 2
        3. 使用场景 3
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: 额外信息
      description: 如果有其他您认为有助于理解这个功能要求的信息，请在这里提供。
