name: Create Random Folder Structure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create random folder and files
        run: |
          FOLDER_NAME=$(head /dev/urandom | tr -dc a-z0-9 | head -c 8)
          mkdir -p "Script details/$FOLDER_NAME"
          FILE_NAME=$(head /dev/urandom | tr -dc a-z0-9 | head -c 8)
          touch "Script details/$FOLDER_NAME/$FILE_NAME.js"
          mkdir -p "Script details/$FOLDER_NAME/Change history"
          echo "# Change History" > "Script details/$FOLDER_NAME/Change history/README.md"

      - name: Push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add random folder structure"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
