name: assign-issue-to-creator

on:
    issues:
        types: [opened]

jobs:
    assign-issue:
        runs-on: ubuntu-latest
        steps:
            - name: 自动分配人民的勤务员
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.BOT_TOKEN }}
                  script: |
                      const issueOwner = context.repo.owner;
                      github.rest.issues.addAssignees({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        assignees: [issueOwner]
                      });
