name: UserScript meta format

on:
  push:
    paths:
      - "**/*.js" # 新的脚本被提交或者被修改了.
      - "!.ChinaGodMan/**"
  workflow_dispatch:

jobs:
  update-chinagodman-commit:
    if: ${{ github.event.commits[0].committer.email == 'china.qinwuyuan@gmail.com' }}
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email  }}
      GIT_COMMITTER_NAME: ChinaGodBot
      GIT_COMMITTER_EMAIL: "${{ secrets.GPG_PRIVATE_EMAIL }}"

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.QWY_SYNC_BOT_TOKEN }}
          fetch-depth: 0

      - name: 设置 Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20.18.0"

      - name: 设置 Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12.4"

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format
        run: |
          python utils/format-changed-scripts.py
      - name: 设置机器人提交
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name 'ChinaGodBot'
          git config --global user.email "${{ secrets.GPG_PRIVATE_EMAIL }}"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
      - name: 提交和推送更改
        run: |
          git pull
          git add .
          git commit -n -m "$ESCAPED_MSG" || true
          git push
          if [ $? -ne 0 ]; then
            git pull --rebase
            git push
          fi
