name: delete branch on close pr
on: 
  pull_request:
    types: [closed]
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置环境变量
        run: |
          echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "PR_MERGED=${{ github.event.pull_request.merged }}" >> $GITHUB_ENV

      - name: 删除分支
        run: |
          if [ "$PR_MERGED" = "true" ]; then
            echo "正在删除分支：$BRANCH_NAME"
            git push origin --delete "$BRANCH_NAME" || true
          else
            echo "PR未合并，跳过删除分支操作。"
          fi
