name: Dependabot auto-merge
on:
    pull_request:
        types: [opened, reopened]
    workflow_call:

permissions:
    contents: write
    pull-requests: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
            - name: install GH CLI
              uses: sersoft-gmbh/setup-gh-cli-action@2d02c06e284b7d55e954d6d6406e7a886f45a818
              with:
                  version: stable
            - name: Enable auto-merge for Dependabot PRs
              run: gh pr merge --auto --rebase "$PR_URL"
              env:
                  PR_URL: ${{github.event.pull_request.html_url}}
                  GITHUB_TOKEN: ${{secrets.QWY_SYNC_BOT_TOKEN}}
