name: flake8lint

on:
  push:
    paths:
      - utils/*.py
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .
