name: "reminder"

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read

jobs:
  reminder:
    permissions:
      issues: write # for agrc/create-reminder-action to set reminders on issues
      pull-requests: write # for agrc/create-reminder-action to set reminders on PRs
    runs-on: ubuntu-latest

    steps:
      - name: check for reminder
        uses: agrc/create-reminder-action@c2025868f56a49dfc239012c78cb8e2beee5554e # v1.1.26
