name: 'check reminders'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  

permissions:
  issues: write
  pull-requests: write

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: check reminders and notify
        uses: agrc/reminder-action@v1
