name: Resync GreasyFork

on:
  workflow_dispatch:

jobs:
  ResyncScripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: 设置 Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12.4"

      - name: 安装依赖
        run: pip install -r utils/requirements.txt

      - name: 重新同步脚本
        run: python utils/script-import-sync.py -s
        env:
          GFU: ${{ secrets.GFU }}
          GFP: ${{ secrets.GFP }}
          GREASYFORK_TOTP_SECRET: ${{ secrets.GREASYFORK_TOTP_SECRET }}
