name: Update Authors

on:
  #push:
    #branches:
    #  - main  # 推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  update-authors:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 运行 authors.sh
      run: bash utils/authors.sh

    - name: 提交和推送更改
      run: |
                  gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
                  git config --global user.name 'qinwuyuan-sync-bot'
                  git config --global user.email "${{ secrets.GPG_PRIVATE_EMAIL }}"
                  git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
                  git pull
                  git add .
                  git commit -S -m "更新→\`[AUTHORS]\`" || echo "没有需要提交的更改"
                  git push
