name: Github 翻译自述文件

on:
  schedule:
    - cron: '0 6 * * *'  # 每天的 UTC 时间 6 点，即中国时间的 14点
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  translate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用你创建的 Token

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install googletrans==4.0.0-rc1  # 安装 Google Translate API 的 Python 包

      - name: 获取当前分支
        id: get_branch
        run: |
          echo "当前分支: $(git rev-parse --abbrev-ref HEAD)"
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: 拉取最新更改
        run: |
          git pull origin ${{ env.branch }}  # 拉取最新的远程更改

      - name: 读取 Load.txt 中的脚本名称
        id: read-script
        run: |
          script_name=$(cat pythonscr/翻译readme_slp/Load.txt)
          script_path="pythonscr/翻译readme_slp/${script_name}"
          echo "script_path=${script_path}" >> $GITHUB_ENV

      - name: 读取并翻译 README
        run: |
          python ${{ env.script_path }}
        continue-on-error: true  # 让这个步骤即使出错也不会终止整个工作流

      - name: 提交和推送更改
        run: |
          # 配置 Git 用户
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 添加更改
          git add .
          git commit -m '自动谷歌翻译 README 文件' || echo "没有需要提交的更改"
          git push origin ${{ env.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # 传递 Token 到 Git 环境变量中
