name: Validate links on push + PR

on:
  #push:
  #pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linkinator:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: JustinBeckwith/linkinator-action@v2.4.3
        with:
          paths: "**/*.md"
          statusCodes: '{ "408": "skip", "429": "skip", "503": "skip" }'
